#!/bin/bash
# install depedencies (if not installed previously)
sudo pacman -Sy --needed gnupg python python-gpgme python-pyqt5 python-pysocks python-requests tor python-gnupg --noconfirm
# set $PWD
cd /home/angel/Downloads
# download tor-browser if file do not exists
[ ! -d "~/Downloads/tor-browser_en-US" ] && wget -c https://www.torproject.org/dist/torbrowser/9.5.4/tor-browser-linux64-9.5.4_en-US.tar.xz | tar -xf tor-browser-linux64-9.5.4_en-US.tar.xz

# (deprecated)
# git clone torbrowser-launcher repository
# git clone https://aur.archlinux.org/torbrowser-launcher-git.git
# make package
# cd torbrowser-launcher-git
# makepkg -si
# cd /home/angel/.local/share/applications

# create folder
mkdir -p ~/.local/share/applications/
# copy launcher into folder
cp ~/Downloads/tor-browser_en-US/start-tor-browser.desktop ~/.local/share/applications/start-tor-browser.desktop
