#!/bin/bash
## Arch linux software installation

# remove unnecesary packages

sudo pacman -R chromium mpv

# install software only if needed 

sudo pacman -Syu libreoffice-fresh-en-gb flameshot tcsh qemu cdrkit wine dlang-dmd fbreader mono udiskie languagetool aspell-en aspell-de aspell-es tree r pandoc cmake aegisub ntfs-3g gpicview git python-pip python-virtualenv python-pipenv python-virtualenvwrapper obs-studio audacious audacious-plugins mpg123 audacity klavaro deluge okular geany firefox gparted dosfstools mtools rsync w3m lynx texlive-most imagemagick jdk-openjdk ccid opensc pcsc-tools youtube-dl perl-xml-parser perl-xml-simple inkscape emacs nvidia nvidia-utils nvidia-settings cuda xorg-server-devel opencl-nvidia --need --noconfirm 
