#!/bin/bash
# run script by: sudo ./install_software(sudo)
# commands will run as sudo unless "sudo -u" is specified

## ------- Arch linux software installation ------- ##

## remove unnecesary packages

pacman -R chromium --noconfirm


## install r statistics

pacman -Sy r

## install rstudio

package=rstudio-desktop-bin
if pacman -Qi $package > /dev/null ; then
    printf 'the package %s is already installed\n' "$package"
else
    initial_dir=$PWD
    cd $HOME/tmp
    # download repository without sudo
    sudo -u angel git clone https://aur.archlinux.org/rstudio-desktop-bin.git
    cd rstudio-desktop-bin
    # compile package without sudo
    sudo -u angel makepkg -Ccsi --noconfirm --needed
    # modify appearence
    mkdir -p /home/angel/.config/rstudio
    # echo prefferences without sudo
    sudo -u angel echo '{
    "editor_theme": "Monokai",
    "pdf_previewer": "none",
    "posix_terminal_shell": "bash",
    "global_theme": "modern"
}
' > /home/angel/.config/rstudio/rstudio-prefs.json
    cd ..
    rm -rf rstudio-desktop-bin
    cd $initial_dir
fi

# install software only if needed 

pacman -Syu --need --noconfirm libreoffice-fresh-en-gb flameshot tcsh qemu cdrkit wine dlang-dmd fbreader mono languagetool aspell-en aspell-de aspell-es tree pandoc cmake aegisub ntfs-3g gpicview git python-pip python-virtualenv python-pipenv python-virtualenvwrapper obs-studio audacious audacious-plugins mpg123 audacity klavaro deluge okular geany firefox gparted dosfstools mtools rsync w3m lynx texlive-most imagemagick jdk-openjdk ccid opensc pcsc-tools youtube-dl perl-xml-parser perl-xml-simple inkscape emacs nvidia nvidia-utils nvidia-settings cuda xorg-server-devel opencl-nvidia 

# deprecated
# pacman -Syu udiskie
