#!/bin/bash
# run script by: sudo ./install_software(sudo)
# commands will run as sudo unless "sudo -u" is specified

## ------- Arch linux software installation ------- ##

## remove unnecesary packages

# pacman -R chromium blueman --noconfirm


## install r statistics

pacman -Sy r --needed --noconfirm

## install rstudio

package=rstudio-desktop-bin
if pacman -Qi $package > /dev/null ; then
    printf 'the package %s is already installed\n' "$package"
else
    initial_dir=$PWD
    cd $HOME/tmp
    # download repository without sudo
    sudo -u angel git clone https://aur.archlinux.org/rstudio-desktop-bin.git
    cd rstudio-desktop-bin
    # compile package without sudo
    sudo -u angel makepkg -Ccsi --noconfirm --needed
    # modify appearence
    mkdir -p /home/angel/.config/rstudio
    # echo prefferences without sudo
    sudo -u angel echo '{
    "editor_theme": "Monokai",
    "pdf_previewer": "none",
    "posix_terminal_shell": "bash",
    "global_theme": "modern"
}
' > /home/angel/.config/rstudio/rstudio-prefs.json
    cd ..
    rm -rf rstudio-desktop-bin
    cd $initial_dir
fi

# install software only if needed 

pacman -Syu --needed --noconfirm screenfetch deluge deluge-gtk blueberry p7zip gitg gsettings-desktop-schemas libreoffice-fresh-en-gb flameshot tcsh qemu cdrkit wine dlang-dmd fbreader mono languagetool aspell-en aspell-de aspell-es tree pandoc cmake aegisub ntfs-3g gpicview git python-pip python-virtualenv python-pipenv python-virtualenvwrapper obs-studio audacious audacious-plugins mpg123 audacity klavaro deluge okular geany firefox gparted dosfstools mtools rsync w3m lynx texlive-most imagemagick jdk-openjdk ccid opensc pcsc-tools youtube-dl perl-xml-parser perl-xml-simple inkscape emacs

# FIXME 2020-10-06 missing icons in cinnamon
# pacman -Sy --needed --noconfirm adwaita-icon-theme akonadiconsole breeze-icons gnome-icon-theme-symbolic icon-naming-utils kemoticons oxygen-icons oxygen-icons-svg
# test this code to check if previous line is required or not (2020-10-08)
# ;testing
# pacman -Sy --needed --noconfirm oxygen-icons oxygen-icons-svg
pacman -Sy --needed --noconfirm $(pacman -Ssq icons)
pacman -Sy --needed --noconfirm $(pacman -Ssq roboto)
pacman -Sy --needed --noconfirm $(pacman -Ssq ttf icon)

## nvidia support

# install nvidia drivers (remenber tu use nvidia-lts in linux-lts)

pacman -Sy --needed --noconfirm nvidia-lts nvidia-utils nvidia-settings xorg-server-devel opencl-nvidia

## error during cuda-11.1.0-2-x86_64 pacman installing (2020-10-06)
# code: pacman -Sy cuda
# error: cuda: key "C5A5958FD7785FAD982FA2EC5A45B06B81CAB876" is unknown
# error: failed to commit transaction (invalid or corrupted package (PGP signature))
# Errors occurred, no packages were upgraded.

## Solution: download it and install it
url="https://ftp5.gwdg.de/pub/linux/archlinux/community/os/x86_64/cuda-11.1.0-2-x86_64.pkg.tar.zst" | FILE=$(basename -- $url)
# sudo -u angel wget "$url" -P /tmp/
# print "installing ${FILE}\n"
# pacman -U "/tmp/$FILE"
pacman -U "/run/media/angel/w7Black/Instaladores_7N/CUDA/archlinux/$FILE" --noconfirm

## pacman: install packages offline
# source: https://wiki.archlinux.org/index.php/Offline_installation_of_packages
