#!/bin/bash

## 5_NCBI_Edirect_install
# source: https://dataguide.nlm.nih.gov/edirect/install.html#unix-command-line-environment

cd ~
# /bin/bash
perl -MNet::FTP -e \
    '$ftp = new Net::FTP("ftp.ncbi.nlm.nih.gov", Passive => 1);
    $ftp->login; $ftp->binary;
    $ftp->get("/entrez/entrezdirect/edirect.tar.gz");'
gunzip -c edirect.tar.gz | tar xf -
rm edirect.tar.gz
builtin exit
export PATH=$PATH:$HOME/edirect >& /dev/null || setenv PATH "${PATH}:$HOME/edirect"
./edirect/setup.sh

# test entrez edirect installation

echo "***********************" > installconfirm
echo "esearch version:" >> installconfirm
esearch -version >> installconfirm
echo "xtract version:" >> installconfirm
xtract -version >> installconfirm
echo "EDirect install status:" >> installconfirm
esearch -db pubmed -query "Babalobi OO[au] AND 2008[pdat]" | \
efetch -format xml | \
xtract -pattern Author -if Affiliation -contains Medicine \
-element Initials >> installconfirm
echo "***********************" >> installconfirm
cat installconfirm
rm installconfirm
