#!/bin/bash
## 8_bash_customization

# bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"

# Install oh-my-bash in custom DIR
# export OSH="/run/media/angel/KN28/emacshome/.linux-config/.dotfiles/oh-my-bash"; sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"

[[ ! -n $(cat ~/.bashrc | grep emacs) ]] && cat /run/media/angel/KN28/emacshome/.linux-config/bash-customization.txt >> ~/.bashrc 

private_directory=/run/media/$USER/KN28
if [[ ! -n $(cat ~/.zshrc | grep 'emacs') ]]; then
    sed -i "s@alias grep='grep --color=auto'@alias grep=\'grep --color=auto'\nalias emacs='emacs -q -l ${private_directory}/init.el'@g" ~/.zshrc
    # git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${private_directory}/powerlevel10k
    git clone https://aur.archlinux.org/yay.git /tmp/yay
    cd /tmp/yay
    makepkg -si
    yay -S --noconfirm zsh-theme-powerlevel10k-git
    
    mkdir -p ~/.local/share/fonts
    cd ~/.local/share/fonts && curl -fLo "Droid Sans Mono for Powerline Nerd Font Complete.otf" https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete.otf
    
    pacman -Qi screenfetch >/dev/null  2>&1 || sudo pacman -Sy screenfetch --noconfirm # && echo 'if [ -f /usr/bin/screenfetch ]; then screenfetch -t; fi' >> ~/.zshrc
fi
